language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"

# command to install dependencies
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install numpy --use-mirrors
  - pip install xlrd --use-mirrors
  - pip install xlsxwriter --use-mirrors
  - pip install openpyxl --use-mirrors
  - pip install coveralls --use-mirrors

# command to run tests
script:
  - nosetests --with-coverage --cover-package=pyexcelerate

after_success:
  - coveralls
